spring:
  application:
    name: service-info
  cloud:
    zookeeper:
      connect-string: zoo1.local:2181,zoo2.local:2182,zoo3.local:2183
---
server:
  port: 35000
spring:
  config:
    activate:
      on-profile: service-info-00
---
server:
  port: 35001
spring:
  config:
    activate:
      on-profile: service-info-01
